// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzznvztokpdtlzcvojar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6em52enRva3BkdGx6Y3ZvamFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjc2NjEsImV4cCI6MjA2OTcwMzY2MX0.TG614sev7TJRONy8T2DcrSKpPXywld3L4fP38pEG1ak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: (url, options = {}) => {
      return fetch(url, {
        ...options,
        // Add timeout to prevent hanging requests
        signal: AbortSignal.timeout(30000),
      }).catch((error) => {
        console.error('Supabase fetch error:', error);
        throw error;
      });
    },
  },
  realtime: {
    params: {
      eventsPerSecond: 2,
    },
  },
});
